# Generated by Django 5.2.17 on 2026-10-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plan_type', models.CharField(max_length=20)),
                ('age_group', models.CharField(max_length=20)),
                ('premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coverage', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField()),
            ],
        ),
    ]
