# Generated by Django 5.2.17 on 2026-10-02 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InsurancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plan_type', models.CharField(choices=[('Basic', 'Basic'), ('Medium', 'Medium'), ('Premium', 'Premium')], max_length=20)),
                ('age_group', models.CharField(choices=[('0-6', '0-6 Years'), ('6-12', '6-12 Years'), ('12+', '12+ Years')], max_length=20)),
                ('premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coverage', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(max_length=50, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(default='Active', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_app.customer')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_app.insuranceplan')),
            ],
        ),
    ]
